Output demo.gif

Require go

Set Shell "bash"
Set FontSize 24
Set FontFamily "JetBrains Mono"
Set TypingSpeed 100ms
Set Width 1280
Set Height 720
Set Theme "catppuccin-mocha"

Hide
Type@0ms `alias terdle="go run . -a charm"` Enter
Type@0ms "clear" Enter
Show

Type "terdle" Sleep 500ms Enter

Sleep 2s

Type "audio" Sleep 500ms Enter
Sleep 1s
Type "cobra" Sleep 500ms Enter
Sleep 1s
Type "churc" Enter Sleep 500ms Backspace 3 Sleep 500ms
Type "arm" Sleep 700ms Enter

Sleep 2s

